version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: review_langchain_app
    ports:
      - "5000:5000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - FLASK_ENV=development
    volumes:
      # Aponta apenas para a pasta de dados, preservando o codigo Python intacto
      - db_data:/app/data

volumes:
  db_data: